---

- name: Deploy MariaDB server
  docker_container:
    image: mariadb
    name: mariadb
    volumes:
      - "{{db_volume}}:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: nopassword
      MYSQL_PASSWORD: nopassword
      MYSQL_DATABASE: db
      MYSQL_USER: admin

- name: Deploy WordPress
  docker_container:
    image: wordpress
    name: wordpress
    restart_policy: always
    ports:
      - "80:80"
    links:
      - "{{db_volume}}:/var/lib/mysql"
    volumes:
      - "{{wordpress}}:/var/www/html"
    env:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_PASSWORD: nopassword
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_NAME: db
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WPLANG', 'en_US');


- name: Download wordpress CLI
  shell: |
    sudo docker exec wordpress curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

- name: Change permissions to wp-cli
  shell: |
    sudo docker exec wordpress chmod +x wp-cli.phar

- name: Configure wp-cli to be in the right path
  shell: |
    sudo docker exec wordpress mv wp-cli.phar /usr/local/bin/wp

- name: Configure wordpress and make a test blog post
  shell: |
    sudo docker exec wordpress wp core install --url=weatherupdate.online --title="Weather Update" --admin_user=RohanChannagiri97 --admin_password=RohanChannagiri97 --admin_email=ADMIN_EMAIL@test.com --allow-root
    sudo docker exec wordpress wp post create --post_title="Weather Update" --post_status=publish --allow-root