- name: Create EC2 instances
  ec2_instance:
    key_name: "{{ key_name }}"
    region: "{{ region_name }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ ami_id }}"
    vpc_subnet_id: "{{ subnet_id }}"
    wait: yes
    tags:
      Name: web
      Env: sandbox
    network:
      assign_public_ip: true
    security_group: "{{ instance_name }}-sg"
  register: ec2

- name: get public ip and add it in the inventory
  shell: |
    aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:Name,Values=web" --output text >> inventory/ec2

- name: Refresh inventory to ensure new instances exist in inventory
  ansible.builtin.meta: refresh_inventory